### PR TITLE
Add CSP workaround hint

### PR DESCRIPTION
**Pull request by Yakov5776**

### CODE REVIEW

**Comment by lewisakura** [comment]
I understand this was in good faith but encouraging people to disable security policy is not something we want to promote. Thank you for the contribution, however!

**Comment by Yakov5776** [comment]
> I understand this was in good faith but encouraging people to disable security policy is not something we want to promote. Thank you for the contribution, however!

Understood. Any plans on making the userscript CSP-Compatible without requiring the Chrome extension (Requires a Chromium browser) or vesxtop?

**Comment by Vendicated** [comment]
no because it's not possible, like you've been told many times already

why are you still inquiring about this?

**Comment by Cynosphere** [comment]
> without requiring the Chrome extension

1. Install [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/)
2. Go to `about:profiles` and click "Set as default profile" on the profile that ends with `.default` to "migrate" (switch to) your Firefox stable profile
3. Clone Vencord, run `pnpm i`, run `pnpm run buildWeb`
4. Open `about:addons`, drag and drop `dist/extension-firefox.zip` into the page, click "Add"

**Pull request closed without merging**
