### PR TITLE
add -E arg to sudo to preserve wayland env vars

### PR DESCRIPTION
**Pull request by TotalChaos05**

### CODE REVIEW

**Comment by Vendicated** [comment]
there shouldn't be any need for this and it is terrible security practice so I don't want to encourage it. Thanks anyway!

**Comment by TotalChaos05** [comment]
without it you cant run the gui on wayland though

**Comment by Vendicated** [comment]
https://github.com/Vencord/Installer/blob/main/install.sh#L21

**Comment by TotalChaos05** [comment]
im just gonna take your word for it, because i patch it using nix now :P
slightly related question, why is `sudo -E` less secure than `sudo`?

**Comment by Vendicated** [comment]
since it keeps all environemnt variables, it makes it so an attacker with normal user access could get root access, via many many many attack vectors (PATH, LD_PRELOAD, etc)

**Comment by unknown134563** [comment]
can you add vesktop on chrome web store as a app plss

**Pull request closed without merging**
