### PR TITLE
Add cute logo

### PR DESCRIPTION
**Pull request by D3SOX**
I haven't worked with Astro before so I'm not sure if this way is okay. If not please tell me how to do it properly

### CODE REVIEW

**Comment by lewisakura** [comment]
preferably you'd want to do the query checking serverside, rather than clientside, using `Astro.url.searchParams`

but also i think we could just use this logo as the actual wordmark because it is absolutely adorable, but lets hear what @Vendicated thinks

**Comment by Vendicated** [comment]
> preferably you'd want to do the query checking serverside, rather than clientside, using Astro.url.searchParams

that's not really possible because the site is a hybrid of prerendered and server side rendered

**Comment by Vendicated** [comment]
the png is quite large at over half a MB. why not optimise it? 

for example as [avif](https://cdn.discordapp.com/attachments/1216096100382019634/1235747473381789777/cute-logo.avif?ex=66357f04&is=66342d84&hm=7d2f9da2398191b4a535dbf1ec995ba3ad60cb4402cfa539465fd7efc9a41a18&), down from 600kb to 40kb

**Comment by lewisakura** [comment]
thank you!

**Pull request merged**
